ALTER TABLE package_redeem_sale_rebates
    ADD COLUMN IF NOT EXISTS purchase_order_id BIGINT NULL REFERENCES payment_orders(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS base_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rebate_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rebate_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS reason VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS error TEXT NULL,
    ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ NULL;
